services:
  botasurvey:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: botasurvey
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
    env_file:
      - .env.local
    environment:
      - NODE_ENV=production
      - DATABASE_PATH=data/db.sqlite
      - HOSTNAME=0.0.0.0
